### ISSUE TITLE
having trouble making variables accesible in multiple js files. not sure what correct approach is

### ISSUE THREAD

**Issue by nleibow** [git-clay/Project_3#17]
http://stackoverflow.com/questions/4396804/access-server-side-variable-on-client-side-and-vice-versa-asp-net-and-javascript

http://stackoverflow.com/questions/17199345/passing-a-variable-from-access-frontend-to-sql-backend-stored-procedure

**Comment by ZebGirouard** [comment]
Talked to Nate about this, it's all set.
